### ISSUE TITLE
No prev commits in git log

### ISSUE THREAD

**Issue by rozhuk-im** [mpoletiek/py3-CHIRP#15]
I wonder: why all commits history dropped?
guthub can import mercurial repos and convert it: https://github.com/rozhuk-im/chirp

**Comment by mpoletiek** [comment]
No specific reason. I started locally with the mercurial repo and made a ton of changes to get it working in Python 3 on Gentoo. 

Once I had it working I uploaded what I had to github so I could keep track of my own changes since the main mercurial branch for py3 wasn't responsive. After receiving a few requests I made it public.

Keep in mind this isn't the "main" main branch from mercurial, this was the py3 branch which I believe hasn't moved since February 2020.

**Comment by rozhuk-im** [comment]
I can try to cherry-pick and rebase all commits from this repo, but I need to know what commit was base for initial commit in this repo.

**Comment by mpoletiek** [comment]
It's in the README.
