### ISSUE TITLE
Refresh from Upstream (and project status)

### ISSUE THREAD

**Issue by masenf** [mpoletiek/py3-CHIRP#21]
@mpoletiek wondering what your interest level is in updating this fork to be even with upstream patches?

I noticed that a snapshot of the source here is actually [distributed as the default "chirp" package in debian](https://packages.debian.org/bullseye/chirp), but that over 100 commits have gone into the upstream since that release.

I've recently started developing some radio drivers for chirp, and eventually found my way over to this repo, which has nice python 3 support and has been updated to use a non-dead widget toolkit (that IMO is nicer to work with).

I'd be really stoked to get automatic patches from upstream and CI builds going. I have some python packaging experience and would be willing to see what it would take to get this going.

Most modern distros aren't even shipping a python2.7 interpreter, and I'm philosophically opposed to the flatpak, so here we are...

**Comment by mpoletiek** [comment]
Honestly, I'd love to, but I currently have conflicting priorities taking all my time. 

I was hoping to come back to this eventually and discover that most of the changes were in the driver space instead of core functionality.

Fortunately I was able to get the most readily available HHUs working (baofengs), so I was hoping someone might have more time and passion to pick up the ball either here or in the community surrounding the main project at danplanet. Unfortunately, I haven't seen anyone who was willing to write code get anywhere with the way the main project is maintained.

I don't have any issues with someone picking up the torch here and driving progress. I simply don't have time. A lot of options for collaboration or running solo.

**Comment by mpoletiek** [comment]
Open to a working PR.
